### ISSUE TITLE
Alert :There was an error fetching your accounts.

### ISSUE THREAD

**Issue by ish3lan** [arvindkalra/box#12]
First I want to highlight this:
In read me there is `npm server.js` did you mean `node server.js`

The main point is: 
I see this message from metamask in the console:
``` inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see ``` [https://bit.ly/2QQHXvF](https://bit.ly/2QQHXvF) ``` for complete information and up-to-date example code.``` 
and I get this error:
1. alert is not defined at line 15 in app.js

Should it be updated to have `provider.enable()`?

**Comment by pranav-singhal** [comment]
the code has been updated since you raised the issue. Can you run it again and see if it still persists?
