### ISSUE TITLE
How to use metaMask with express?

### ISSUE THREAD

**Issue by Sunnykaby** [arvindkalra/box#3]
I just install the metaMask plugin into the chrome. and run the project with npm start. 
Then I found the backend(express server) can't find the metamask, and create a new wed3 provider.
Because the metamask is a chrome plugin, and how can I use the metamask's provider?

**Comment by harksha** [comment]
I don't think you are supposed to use metamask on the server side. just use a regular ethereum node to connect (f. eg. https://infura.io/)
