### ISSUE TITLE
Unboxing fails, throwing an error

### ISSUE THREAD

**Issue by harksha** [arvindkalra/box#6]
npm ERR! code 128
npm ERR! Command failed: C:\Users\myUser\AppData\Local\Programs\Git\cmd\git.EXE clone -q https://github.com/debris/bignumber.js.git C:\Users\myUser\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-af206b19 --config core.longpaths=true
npm ERR! warning: templates not found C:\Users\myUser\AppData\Local\Temp\pacote-git-template-tmp\git-clone-00db848d
npm ERR! fatal: early EOF
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: index-pack failed
npm ERR! error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myUser\AppData\Roaming\npm-cache\_logs\2018-05-01T08_57_08_479Z-debug.log

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

OS: Win10
Node: 9.3.0
NPM: 5.5.1

**Comment by pranav-singhal** [comment]
did u try to clone the repo or  did u run 'truffle unbox arvindkalra/express-box' ?

**Comment by pranav-singhal** [comment]
this looks similar to npm/npm/issues/17413
