### ISSUE TITLE
Remove metamask

### ISSUE THREAD

**Issue by 7flash** [arvindkalra/box#7]
How metamask could be connected on backend?

https://github.com/arvindkalra/express-box/blob/894108142b893b2a1a23fd01fee3304dfb04760a/server.js#L57

**Comment by pranav-singhal** [comment]
metamask is a front-end wallet... It is not required, thus not used on the backend.

**Comment by 7flash** [comment]
@pranav-singhal Exactly, so why do you try to detect metamask on backend?

**Comment by 7flash** [comment]
I mean https://github.com/arvindkalra/express-box/pull/8
